import NAME from "./constants";

export const FILTER_CHANGE = NAME + "/FILTER_CHANGE";

export const REQUEST = NAME + "/REQUEST";
export const REQUEST_REJECTED = NAME + "/REQUEST_REJECTED";

export const GET_USERS_FULFILLED = NAME + "/GET_USERS_FULFILLED";
export const UPDATE_USER_ROLE_FULFILLED = NAME + "/UPDATE_USER_ROLE_FULFILLED";
export const ADD_USER_FULFILLED = NAME + "/ADD_USER_FULFILLED";
export const DELETE_USER_FULFILLED = NAME + "/DELETE_USER_FULFILLED";