import {NAME} from "./constants";

export const UPDATE_GROWTH = NAME + "/UPDATE_GROWTH";
export const UPDATE_GROWTH_FULFILLED = NAME + "/UPDATE_GROWTH_FULFILLED";
export const UPDATE_GROWTH_REJECTED = NAME + "/UPDATE_GROWTH_REJECTED";

export const UPDATE_RECORDS_INFO = NAME + "/UPDATE_RECORDS_INFO";
export const UPDATE_RECORDS_INFO_FULFILLED = NAME + "/UPDATE_RECORDS_INFO_FULFILLED";
export const UPDATE_RECORDS_INFO_REJECTED = NAME + "/UPDATE_RECORDS_INFO_REJECTED";

export const UPDATE_STATISTIC = NAME + "/UPDATE_STATISTIC";
export const UPDATE_STATISTIC_REJECTED = NAME + "/UPDATE_STATISTIC_REJECTED";